# $name = player name
# $time = current time
# ยง = color tag
# \n = new line

#custom time format
#h = hours; i = minutes; s = seconds
timeFormat: 'h:i:s'

joinEnable: true #true = enabled; false = disabled
join: "Change me In config.yml at Line 11"

leaveEnable: true #true = enabled; false = disabled
leave: "Change me In config.yml at Line 14"

firstTimeEnable: false #true = enabled; false = disabled
firstTimeJoin: "Change me!"
# Maded By ThorMagHunde and Hope20
# Normal Lanuage: Italiano, New Lanuage: English
# Plugin: ThorMagHunde
