# $name = player name
# $time = current time
# § = color tag
# \n = new line

#custom time format
#h = hours; i = minutes; s = seconds
timeFormat: 'h:i:s'

joinEnable: true #true = enabled; false = disabled
join: "§8[§a+§8] §7$name"

leaveEnable: true #true = enabled; false = disabled
leave: "§8[§c-§8] §7$name"

firstTimeEnable: false #true = enabled; false = disabled
firstTimeJoin: "Change me!"
# Maded By ThorMagHunde and Hope20
# Normal Lanuage: Italiano, New Lanuage: English
# Plugin: ThorMagHunde
# Changelog:
# Fixed config.yml
